apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicpredictor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: musicpredictor
  template:
    metadata:
      labels:
        app: musicpredictor
    spec:
      containers:
      - name: cv-app
        image: gcr.io/$PROJECT_ID/mymusicpredictor
        ports:
        - containerPort: 8501
